#!/usr/bin/env python3
"""Plot mean p-values for the banker's rounding experiment.

Reads data files generated by generate_mean_p_values.py.
Supports files with 3 columns (N, ct, chi2) or 4 columns (N, ct, chi2, gtest).
"""

import argparse
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def auto_crop(path):
    import cv2
    img = cv2.imread(path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    coords = cv2.findNonZero(255 - gray)
    if coords is not None:
        x, y, w, h = cv2.boundingRect(coords)
        img = img[y:y + h, x:x + w]
        cv2.imwrite(path, img)


def plot_mean_p_values(d, step, lower_N, upper_N, save_path, input_path=None,
                       ylim_lower=None, ylim_upper=None, crop=False):
    if input_path is None:
        input_path = "../data/mean_p_values_d_%d_step_%d.txt" % (d, step)

    data = np.loadtxt(input_path)

    Ns = data[:, 0]
    mask = (Ns >= lower_N) & (Ns <= upper_N)
    data = data[mask, :]
    Ns = data[:, 0]

    n_cols = data.shape[1]
    # Column layout: N, ct, [chi2], [gtest]
    ct_ps = data[:, 1]

    tick_fontsize = 22
    label_fontsize = 36

    matplotlib.rc("font", size=tick_fontsize)
    fig, ax = plt.subplots(figsize=(13, 8))
    ax.set_xlabel("$N$", fontsize=label_fontsize)
    ax.set_ylabel("$p$-value", fontsize=label_fontsize)

    ax.plot(Ns, ct_ps, label="mean CT $p$-value")
    if n_cols >= 3:
        chi2_ps = data[:, 2]
        ax.plot(Ns, chi2_ps, label="mean Pearson's chi-square test $p$-value")
    if n_cols >= 4:
        gtest_ps = data[:, 3]
        ax.plot(Ns, gtest_ps, label="mean $G$-test $p$-value")

    ax.plot(Ns, [0.05] * len(Ns), "--", color="red", label="$p=0.05$")
    ax.grid(True, alpha=0.3)
    if ylim_lower is not None or ylim_upper is not None:
        cur_lo, cur_hi = ax.get_ylim()
        ax.set_ylim(ylim_lower if ylim_lower is not None else cur_lo,
                     ylim_upper if ylim_upper is not None else cur_hi)
    ax.legend(fontsize=tick_fontsize)
    fig.tight_layout()
    fig.savefig(save_path, format="png", dpi=300)
    plt.close(fig)
    if crop:
        auto_crop(save_path)
    print("Saved: %s" % save_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Plot mean p-values for banker's rounding experiment.")
    parser.add_argument("-d", type=int, default=0,
                        help="Number of decimal places (default: 0)")
    parser.add_argument("--step", type=int, default=100,
                        help="Step size used in data generation (default: 100)")
    parser.add_argument("--lower-N", type=int, default=2,
                        help="Lower bound for N (default: 2)")
    parser.add_argument("--upper-N", type=int, default=3000,
                        help="Upper bound for N (default: 3000)")
    parser.add_argument("--ylim-lower", type=float, default=None,
                        help="Lower y-axis limit (default: auto)")
    parser.add_argument("--ylim-upper", type=float, default=None,
                        help="Upper y-axis limit (default: auto)")
    parser.add_argument("--crop", action="store_true",
                        help="Auto-crop white margins from the output image")
    parser.add_argument("-i", "--input", type=str, default=None,
                        help="Input data file (default: mean_p_values_d_{d}_step_{step}.txt)")
    parser.add_argument("-o", "--output", type=str, default=None,
                        help="Output file path (default: paper/img/mean_p_values_d_{d}_step_{step}.png)")
    args = parser.parse_args()

    if args.output is None:
        save_path = "../paper/img/mean_p_values_d_%d_step_%d.png" % (args.d, args.step)
    else:
        save_path = args.output

    plot_mean_p_values(d=args.d, step=args.step, lower_N=args.lower_N,
                       upper_N=args.upper_N, save_path=save_path,
                       input_path=args.input,
                       ylim_lower=args.ylim_lower, ylim_upper=args.ylim_upper,
                       crop=args.crop)
